namespace ALPS_Application.Migrations
{
    using ALPS_Application.Models;
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<ALPS_Application.Models.DatabaseContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            ContextKey = "ALPS_Application.Models.DatabaseContext";
        }

        protected override void Seed(ALPS_Application.Models.DatabaseContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.

            /*created with Ruby script:
            require 'csv'
            d = CSV.read("Migrations/States.txt")
            d.each_with_index{ |x,i| puts "new USState() { ID = #{i+1}, Name = \"#{x[0]}\", Abbreviation = \"#{x[1]}\" }," }
            d.each_with_index{ |x,i| puts "new Employee() { ID = #{i+1}, FirstName = \"#{x[0]}\", LastName = \"#{x[1]}\", OfficeId = #{rand(4)+1} }," }
            */
            context.USStates.AddOrUpdate(x => x.ID,
                new USState() { ID = 1, Name = "Alabama", Abbreviation = "AL" },
                new USState() { ID = 2, Name = "Alaska", Abbreviation = "AK" },
                new USState() { ID = 3, Name = "Arizona", Abbreviation = "AZ" },
                new USState() { ID = 4, Name = "Arkansas", Abbreviation = "AR" },
                new USState() { ID = 5, Name = "California", Abbreviation = "CA" },
                new USState() { ID = 6, Name = "Colorado", Abbreviation = "CO" },
                new USState() { ID = 7, Name = "Connecticut", Abbreviation = "CT" },
                new USState() { ID = 8, Name = "Delaware", Abbreviation = "DE" },
                new USState() { ID = 9, Name = "Florida", Abbreviation = "FL" },
                new USState() { ID = 10, Name = "Georgia", Abbreviation = "GA" },
                new USState() { ID = 11, Name = "Hawaii", Abbreviation = "HI" },
                new USState() { ID = 12, Name = "Idaho", Abbreviation = "ID" },
                new USState() { ID = 13, Name = "Illinois", Abbreviation = "IL" },
                new USState() { ID = 14, Name = "Indiana", Abbreviation = "IN" },
                new USState() { ID = 15, Name = "Iowa", Abbreviation = "IA" },
                new USState() { ID = 16, Name = "Kansas", Abbreviation = "KS" },
                new USState() { ID = 17, Name = "Kentucky", Abbreviation = "KY" },
                new USState() { ID = 18, Name = "Louisiana", Abbreviation = "LA" },
                new USState() { ID = 19, Name = "Maine", Abbreviation = "ME" },
                new USState() { ID = 20, Name = "Maryland", Abbreviation = "MD" },
                new USState() { ID = 21, Name = "Massachusetts", Abbreviation = "MA" },
                new USState() { ID = 22, Name = "Michigan", Abbreviation = "MI" },
                new USState() { ID = 23, Name = "Minnesota", Abbreviation = "MN" },
                new USState() { ID = 24, Name = "Mississippi", Abbreviation = "MS" },
                new USState() { ID = 25, Name = "Missouri", Abbreviation = "MO" },
                new USState() { ID = 26, Name = "Montana", Abbreviation = "MT" },
                new USState() { ID = 27, Name = "Nebraska", Abbreviation = "NE" },
                new USState() { ID = 28, Name = "Nevada", Abbreviation = "NV" },
                new USState() { ID = 29, Name = "New Hampshire", Abbreviation = "NH" },
                new USState() { ID = 30, Name = "New Jersey", Abbreviation = "NJ" },
                new USState() { ID = 31, Name = "New Mexico", Abbreviation = "NM" },
                new USState() { ID = 32, Name = "New York", Abbreviation = "NY" },
                new USState() { ID = 33, Name = "North Carolina", Abbreviation = "NC" },
                new USState() { ID = 34, Name = "North Dakota", Abbreviation = "ND" },
                new USState() { ID = 35, Name = "Ohio", Abbreviation = "OH" },
                new USState() { ID = 36, Name = "Oklahoma", Abbreviation = "OK" },
                new USState() { ID = 37, Name = "Oregon", Abbreviation = "OR" },
                new USState() { ID = 38, Name = "Pennsylvania", Abbreviation = "PA" },
                new USState() { ID = 39, Name = "Rhode Island", Abbreviation = "RI" },
                new USState() { ID = 40, Name = "South Carolina", Abbreviation = "SC" },
                new USState() { ID = 41, Name = "South Dakota", Abbreviation = "SD" },
                new USState() { ID = 42, Name = "Tennessee", Abbreviation = "TN" },
                new USState() { ID = 43, Name = "Texas", Abbreviation = "TX" },
                new USState() { ID = 44, Name = "Utah", Abbreviation = "UT" },
                new USState() { ID = 45, Name = "Vermont", Abbreviation = "VT" },
                new USState() { ID = 46, Name = "Virginia", Abbreviation = "VA" },
                new USState() { ID = 47, Name = "Washington", Abbreviation = "WA" },
                new USState() { ID = 48, Name = "West Virginia", Abbreviation = "WV" },
                new USState() { ID = 49, Name = "Wisconsin", Abbreviation = "WI" },
                new USState() { ID = 50, Name = "Wyoming", Abbreviation = "WY" },
                new USState() { ID = 51, Name = "American Samoa", Abbreviation = "AS" },
                new USState() { ID = 52, Name = "District of Columbia", Abbreviation = "DC" },
                new USState() { ID = 53, Name = "Federated States of Micronesia", Abbreviation = "FM" },
                new USState() { ID = 54, Name = "Guam", Abbreviation = "GU" },
                new USState() { ID = 55, Name = "Marshall Islands", Abbreviation = "MH" },
                new USState() { ID = 56, Name = "Northern Mariana Islands", Abbreviation = "MP" },
                new USState() { ID = 57, Name = "Palau", Abbreviation = "PW" },
                new USState() { ID = 58, Name = "Puerto Rico", Abbreviation = "PR" },
                new USState() { ID = 59, Name = "Virgin Islands", Abbreviation = "VI" }
                );

            context.Offices.AddOrUpdate(x => x.ID,
                new Office() { ID = 1, City = "Denver", USStateId = 6 },
                new Office() { ID = 2, City = "Boston", USStateId = 21 },
                new Office() { ID = 3, City = "San Francisco", USStateId = 5 },
                new Office() { ID = 4, City = "New York City", USStateId = 32 }
                );

            context.Employees.AddOrUpdate(x => x.ID,
                new Employee() { ID = 1, FirstName = "Terrell", LastName = "Lane", OfficeId = 1 },
                new Employee() { ID = 2, FirstName = "Carolyn", LastName = "Schmitt", OfficeId = 4 },
                new Employee() { ID = 3, FirstName = "Mohammad", LastName = "Crane", OfficeId = 3 },
                new Employee() { ID = 4, FirstName = "Aubrie", LastName = "Mullins", OfficeId = 4 },
                new Employee() { ID = 5, FirstName = "Slade", LastName = "Madden", OfficeId = 4 },
                new Employee() { ID = 6, FirstName = "Sydney", LastName = "Hensley", OfficeId = 1 },
                new Employee() { ID = 7, FirstName = "Athena", LastName = "Reeves", OfficeId = 2 },
                new Employee() { ID = 8, FirstName = "Brayden", LastName = "Prince", OfficeId = 1 },
                new Employee() { ID = 9, FirstName = "Landyn", LastName = "Holloway", OfficeId = 2 },
                new Employee() { ID = 10, FirstName = "Tara", LastName = "Mayer", OfficeId = 1 },
                new Employee() { ID = 11, FirstName = "Aidyn", LastName = "Willis", OfficeId = 4 },
                new Employee() { ID = 12, FirstName = "Sterling", LastName = "Sweeney", OfficeId = 2 },
                new Employee() { ID = 13, FirstName = "Landin", LastName = "Flynn", OfficeId = 4 },
                new Employee() { ID = 14, FirstName = "Lane", LastName = "Rowland", OfficeId = 4 },
                new Employee() { ID = 15, FirstName = "Lorenzo", LastName = "Doyle", OfficeId = 3 },
                new Employee() { ID = 16, FirstName = "Selina", LastName = "Fields", OfficeId = 1 },
                new Employee() { ID = 17, FirstName = "Nathanael", LastName = "Villarreal", OfficeId = 3 },
                new Employee() { ID = 18, FirstName = "Clinton", LastName = "Bentley", OfficeId = 3 },
                new Employee() { ID = 19, FirstName = "Valery", LastName = "Monroe", OfficeId = 3 },
                new Employee() { ID = 20, FirstName = "Kai", LastName = "Giles", OfficeId = 4 },
                new Employee() { ID = 21, FirstName = "Joseph", LastName = "Nixon", OfficeId = 4 },
                new Employee() { ID = 22, FirstName = "Nathalia", LastName = "Herrera", OfficeId = 1 },
                new Employee() { ID = 23, FirstName = "Rodrigo", LastName = "Mercado", OfficeId = 1 },
                new Employee() { ID = 24, FirstName = "Arielle", LastName = "Ellison", OfficeId = 3 },
                new Employee() { ID = 25, FirstName = "Alannah", LastName = "Hanna", OfficeId = 4 },
                new Employee() { ID = 26, FirstName = "Keira", LastName = "Watkins", OfficeId = 1 },
                new Employee() { ID = 27, FirstName = "Roberto", LastName = "Parks", OfficeId = 4 },
                new Employee() { ID = 28, FirstName = "Cooper", LastName = "Foster", OfficeId = 3 },
                new Employee() { ID = 29, FirstName = "Brian", LastName = "Strickland", OfficeId = 3 },
                new Employee() { ID = 30, FirstName = "Lacey", LastName = "Vaughan", OfficeId = 2 },
                new Employee() { ID = 31, FirstName = "Tate", LastName = "James", OfficeId = 3 },
                new Employee() { ID = 32, FirstName = "Maryjane", LastName = "Henderson", OfficeId = 4 },
                new Employee() { ID = 33, FirstName = "Graham", LastName = "Peters", OfficeId = 4 },
                new Employee() { ID = 34, FirstName = "Darren", LastName = "Cummings", OfficeId = 3 },
                new Employee() { ID = 35, FirstName = "Alexia", LastName = "Alvarez", OfficeId = 1 },
                new Employee() { ID = 36, FirstName = "Renee", LastName = "Ponce", OfficeId = 2 },
                new Employee() { ID = 37, FirstName = "Brennen", LastName = "Howell", OfficeId = 2 },
                new Employee() { ID = 38, FirstName = "Martha", LastName = "Benitez", OfficeId = 2 },
                new Employee() { ID = 39, FirstName = "Andre", LastName = "Wood", OfficeId = 2 },
                new Employee() { ID = 40, FirstName = "Keegan", LastName = "Joseph", OfficeId = 2 },
                new Employee() { ID = 41, FirstName = "Winston", LastName = "Robertson", OfficeId = 3 },
                new Employee() { ID = 42, FirstName = "Arthur", LastName = "Cordova", OfficeId = 1 },
                new Employee() { ID = 43, FirstName = "Maximilian", LastName = "English", OfficeId = 4 },
                new Employee() { ID = 44, FirstName = "Mikaela", LastName = "Holden", OfficeId = 1 },
                new Employee() { ID = 45, FirstName = "Caitlin", LastName = "Sandoval", OfficeId = 1 },
                new Employee() { ID = 46, FirstName = "Donna", LastName = "Spence", OfficeId = 1 },
                new Employee() { ID = 47, FirstName = "Josie", LastName = "Chavez", OfficeId = 2 },
                new Employee() { ID = 48, FirstName = "Brylee", LastName = "Anderson", OfficeId = 4 },
                new Employee() { ID = 49, FirstName = "Lydia", LastName = "Maxwell", OfficeId = 3 },
                new Employee() { ID = 50, FirstName = "Elena", LastName = "Black", OfficeId = 4 },
                new Employee() { ID = 51, FirstName = "Enzo", LastName = "Hayden", OfficeId = 3 },
                new Employee() { ID = 52, FirstName = "Gillian", LastName = "Hess", OfficeId = 1 },
                new Employee() { ID = 53, FirstName = "Addison", LastName = "Mejia", OfficeId = 4 },
                new Employee() { ID = 54, FirstName = "Broderick", LastName = "Ingram", OfficeId = 3 },
                new Employee() { ID = 55, FirstName = "Karlee", LastName = "Castro", OfficeId = 2 },
                new Employee() { ID = 56, FirstName = "Jason", LastName = "Carter", OfficeId = 1 },
                new Employee() { ID = 57, FirstName = "Dario", LastName = "Fernandez", OfficeId = 3 },
                new Employee() { ID = 58, FirstName = "Ava", LastName = "Ellis", OfficeId = 4 },
                new Employee() { ID = 59, FirstName = "Colton", LastName = "Pope", OfficeId = 2 },
                new Employee() { ID = 60, FirstName = "Autumn", LastName = "Villegas", OfficeId = 4 },
                new Employee() { ID = 61, FirstName = "Taylor", LastName = "Hardy", OfficeId = 3 },
                new Employee() { ID = 62, FirstName = "Frances", LastName = "Duke", OfficeId = 3 },
                new Employee() { ID = 63, FirstName = "Madelyn", LastName = "Chandler", OfficeId = 1 },
                new Employee() { ID = 64, FirstName = "Eliezer", LastName = "Wilcox", OfficeId = 1 },
                new Employee() { ID = 65, FirstName = "Eve", LastName = "Roy", OfficeId = 4 },
                new Employee() { ID = 66, FirstName = "Emilee", LastName = "Jimenez", OfficeId = 2 },
                new Employee() { ID = 67, FirstName = "Andreas", LastName = "Herman", OfficeId = 3 },
                new Employee() { ID = 68, FirstName = "Douglas", LastName = "Li", OfficeId = 2 },
                new Employee() { ID = 69, FirstName = "Cash", LastName = "Lang", OfficeId = 4 },
                new Employee() { ID = 70, FirstName = "Tiana", LastName = "Lynn", OfficeId = 3 },
                new Employee() { ID = 71, FirstName = "Zander", LastName = "Choi", OfficeId = 4 },
                new Employee() { ID = 72, FirstName = "Finn", LastName = "Zhang", OfficeId = 2 },
                new Employee() { ID = 73, FirstName = "Zaria", LastName = "Stanley", OfficeId = 2 },
                new Employee() { ID = 74, FirstName = "Christian", LastName = "Garrison", OfficeId = 1 },
                new Employee() { ID = 75, FirstName = "Willie", LastName = "Hooper", OfficeId = 2 },
                new Employee() { ID = 76, FirstName = "Chaim", LastName = "Arroyo", OfficeId = 1 },
                new Employee() { ID = 77, FirstName = "Elyse", LastName = "Blackwell", OfficeId = 4 },
                new Employee() { ID = 78, FirstName = "Case", LastName = "Cortez", OfficeId = 2 },
                new Employee() { ID = 79, FirstName = "Adelyn", LastName = "Adams", OfficeId = 1 },
                new Employee() { ID = 80, FirstName = "Darien", LastName = "Bradley", OfficeId = 4 },
                new Employee() { ID = 81, FirstName = "Kendrick", LastName = "Moses", OfficeId = 1 },
                new Employee() { ID = 82, FirstName = "Keagan", LastName = "Ho", OfficeId = 1 },
                new Employee() { ID = 83, FirstName = "Konnor", LastName = "Gross", OfficeId = 1 },
                new Employee() { ID = 84, FirstName = "Kaylie", LastName = "Whitaker", OfficeId = 3 },
                new Employee() { ID = 85, FirstName = "Avery", LastName = "Maynard", OfficeId = 4 },
                new Employee() { ID = 86, FirstName = "Liam", LastName = "Burch", OfficeId = 4 },
                new Employee() { ID = 87, FirstName = "Brendon", LastName = "Mendoza", OfficeId = 4 },
                new Employee() { ID = 88, FirstName = "Andrea", LastName = "Harding", OfficeId = 3 },
                new Employee() { ID = 89, FirstName = "Stanley", LastName = "Arellano", OfficeId = 4 },
                new Employee() { ID = 90, FirstName = "Hector", LastName = "Gonzalez", OfficeId = 2 },
                new Employee() { ID = 91, FirstName = "Harrison", LastName = "Cruz", OfficeId = 2 },
                new Employee() { ID = 92, FirstName = "Albert", LastName = "Curry", OfficeId = 3 },
                new Employee() { ID = 93, FirstName = "Deacon", LastName = "Crawford", OfficeId = 2 },
                new Employee() { ID = 94, FirstName = "Deegan", LastName = "Gomez", OfficeId = 1 },
                new Employee() { ID = 95, FirstName = "Salvatore", LastName = "Strong", OfficeId = 3 },
                new Employee() { ID = 96, FirstName = "Leonidas", LastName = "Winters", OfficeId = 2 },
                new Employee() { ID = 97, FirstName = "Hunter", LastName = "Shields", OfficeId = 2 },
                new Employee() { ID = 98, FirstName = "Bridger", LastName = "Douglas", OfficeId = 2 },
                new Employee() { ID = 99, FirstName = "Kash", LastName = "Benson", OfficeId = 2 },
                new Employee() { ID = 100, FirstName = "Rosa", LastName = "Joyce", OfficeId = 2 }
                );
        }
    }
}
